chore(coverage): add code coverage using codecov
hemal7735/findall-pkg-mgr pull request #9
Opened 2019-01-19 09:22 UTC by devenbansod

* Need to set `CODECOV_TOKEN="<codecov-token>"` environment variable in Travis to get this up and running

@hemal7735 Please go to https://codecov.io/gh/hemal7745/findall-pkg-mgr to get started. Do let me know if you find something missing or awry

2019-01-20 12:27 UTC, hemal7735 requested changes

2019-01-20 12:27 UTC, hemal7735 commented on .travis.yml
> +  - npm install -g codecov
```suggestion
  - travis_wait npm ci
  - npm install -g codecov
```

Default install is `npm install` and if lock files exist then `npm ci`.  Build is failing because we added `install` script , which does not have `npm install` or `npm ci`.

2019-01-20 12:43 UTC, devenbansod commented on .travis.yml
> +  - npm install -g codecov
@hemal7735 Thanks for pointing this out! 👍 Added the suggestion. Build failed with `npm ci` on v6. Trying `npm run ci` instead (failed too).

Do you have an idea?

2019-01-20 13:33 UTC, hemal7735 commented on .travis.yml
> +  - npm install -g codecov
`npm ci` should work. Failures on v6 might be temporary. `npm run ci` should not work, as `npm run <command>` will be picked up from package.json.

2019-01-20 15:14 UTC, devenbansod commented on .travis.yml
> +  - npm install -g codecov
@hemal7735 It seems `npm ci` was only introduced in v5.7.0 https://blog.npmjs.org/post/171139955345/v570

What do you think about adding?
```
before_install:
  - npm i -g npm
```

2019-01-20 17:01 UTC, hemal7735 commented on .travis.yml
> +  - npm install -g codecov
```
before_install:
    - npm install -g npm@latest
```
?

2019-01-21 04:12 UTC, devenbansod commented
@hemal7735 finally green! 👍

2019-01-21 04:52 UTC, hemal7735 commented
@devenbansod , finally! 
Just one qq: https://codecov.io/gh/hemal7735/findall-pkg-mgr/branch/master/graph/badge.svg is still showing `unknown`. Any idea?

2019-01-21 05:38 UTC, devenbansod commented
@hemal7735 I think that's mainly because since this PR is not merged to master branch, codacy is not able to get the coverage for the master branch. 

Should be ideally fixed once this is merged.

2019-01-21 05:46 UTC, hemal7735 approved these changes

2019-01-21 05:46 UTC, merged

2019-01-21 05:48 UTC, hemal7735 commented
@devenbansod yup, worked. Thank you for the PR 💯